<?php
/**
 * Renders the OD Shuffle block.
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Saved block content.
 * @var WP_Block $block      Block instance.
 *
 * @package OD_Shuffle_Block
 */

$od_shuffle_block_candidates = array_values(
	array_filter(
		$block->parsed_block['innerBlocks'] ?? array(),
		static function ( $inner_block ) {
			return 'od/shuffle-item' === ( $inner_block['blockName'] ?? null );
		}
	)
);

if ( empty( $od_shuffle_block_candidates ) ) {
	return;
}

$od_shuffle_block_selected = $od_shuffle_block_candidates[ wp_rand( 0, count( $od_shuffle_block_candidates ) - 1 ) ];
$od_shuffle_block_content  = '';

foreach ( $od_shuffle_block_selected['innerBlocks'] ?? array() as $od_shuffle_block_inner_block ) {
	$od_shuffle_block_content .= render_block( $od_shuffle_block_inner_block );
}

// The wrapper attributes and nested block markup are generated by WordPress.
// phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped
printf(
	'<div %1$s>%2$s</div>',
	get_block_wrapper_attributes(),
	$od_shuffle_block_content
);
// phpcs:enable WordPress.Security.EscapeOutput.OutputNotEscaped
